version: '3.9'
name: flask-app

services:
  db:
    container_name: db_container
    image: postgres:latest
    env_file: ./.docker/database/.db.env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    
  flask_app:
    container_name: flask_app_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    links:
      - db
  
volumes:
  postgres_db:
    driver: local